function psi_next = func_psi_next(in1)
%FUNC_PSI_NEXT
%    PSI_NEXT = FUNC_PSI_NEXT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    25-Jan-2021 11:18:34

y1 = in1(1,:);
y2 = in1(2,:);
y3 = in1(3,:);
y4 = in1(4,:);
t2 = y1.^2;
t3 = y2.^2;
t4 = y3.^2;
t5 = y4.^2;
psi_next = [1.0;y1;t2;t2.*y1;y2;y1.*y2;t2.*y2;t3;t3.*y1;t3.*y2;y3;y1.*y3;t2.*y3;y2.*y3;y1.*y2.*y3;t3.*y3;t4;t4.*y1;t4.*y2;t4.*y3;y4;y1.*y4;t2.*y4;y2.*y4;y1.*y2.*y4;t3.*y4;y3.*y4;y1.*y3.*y4;y2.*y3.*y4;t4.*y4;t5;t5.*y1;t5.*y2;t5.*y3;t5.*y4];
