function psi = func_ff(x1,x2,x3,x4)
%FUNC_FF
%    PSI = FUNC_FF(X1,X2,X3,X4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    25-Jan-2021 10:33:25

psi = [1.0;x1;x1.^2;x2;x1.*x2;x2.^2;x3;x1.*x3;x2.*x3;x3.^2;x4;x1.*x4;x2.*x4;x3.*x4;x4.^2];
