function states = func_psi2x(in1)
%FUNC_PSI2X
%    STATES = FUNC_PSI2X(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Jan-2021 09:32:57

z2 = in1(2,:);
z5 = in1(5,:);
z11 = in1(11,:);
z21 = in1(21,:);
states = [z2;z5;z11;z21];
