function psi = func_psi(in1)
%FUNC_PSI
%    PSI = FUNC_PSI(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Jan-2021 09:32:56

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x1.^2;
t3 = x2.^2;
t4 = x3.^2;
t5 = x4.^2;
psi = [1.0;x1;t2;t2.*x1;x2;x1.*x2;t2.*x2;t3;t3.*x1;t3.*x2;x3;x1.*x3;t2.*x3;x2.*x3;x1.*x2.*x3;t3.*x3;t4;t4.*x1;t4.*x2;t4.*x3;x4;x1.*x4;t2.*x4;x2.*x4;x1.*x2.*x4;t3.*x4;x3.*x4;x1.*x3.*x4;x2.*x3.*x4;t4.*x4;t5;t5.*x1;t5.*x2;t5.*x3;t5.*x4];
