function [value,isterminal,direction] = event_LO(t,in2)
%EVENT_LO
%    [VALUE,ISTERMINAL,DIRECTION] = EVENT_LO(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    16-Feb-2021 14:46:43

Q1 = in2(1,:);
value = Q1-1.0;
if nargout > 1
    isterminal = 1.0;
end
if nargout > 2
    direction = 1.0;
end
