function f = func_f(t,in2)
%FUNC_F
%    F = FUNC_F(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    16-Feb-2021 14:46:43

Q1 = in2(1,:);
Q2 = in2(2,:);
Q3 = in2(3,:);
Q4 = in2(4,:);
t2 = cos(Q2);
t3 = sin(Q2);
t4 = Q3.*t3;
t5 = Q1.*Q4.*t2;
t6 = t4+t5;
t7 = Q3.*t2;
t8 = t7-Q1.*Q4.*t3;
f = [Q3;Q4;Q1.*-4.0e1-t2+Q4.*t2.*t6-Q4.*t3.*t8+4.0e1;Q1.*t3-Q3.*(t2.*t6-t3.*t8+Q1.*Q4.*t2.^2+Q1.*Q4.*t3.^2)];
