function h = func_h(t,in2)
%FUNC_H
%    H = FUNC_H(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    16-Feb-2021 14:46:43

P3 = in2(3,:);
P4 = in2(4,:);
h = [P3;P4;0.0;-1.0];
