function [value,isterminal,direction] = event_TD(t,in2,beta)
%EVENT_TD
%    [VALUE,ISTERMINAL,DIRECTION] = EVENT_TD(T,IN2,BETA)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Jan-2021 11:10:07

P2 = in2(2,:);
value = P2-sin(beta);
if nargout > 1
    isterminal = 1.0;
end
if nargout > 2
    direction = -1.0;
end
