function J = func_J(in1)
%FUNC_J
%    J = FUNC_J(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Jan-2021 11:10:07

Q1 = in1(1,:);
Q2 = in1(2,:);
t2 = cos(Q2);
t3 = sin(Q2);
J = reshape([-t3,t2,-Q1.*t2,-Q1.*t3],[2,2]);
