function f = func_f(t,in2)
%FUNC_F
%    F = FUNC_F(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    12-Jan-2021 11:10:07

Q1 = in2(1,:);
Q2 = in2(2,:);
Q3 = in2(3,:);
Q4 = in2(4,:);
t2 = cos(Q2);
t3 = sin(Q2);
t4 = Q3.*t3;
t5 = Q1.*Q4.*t2;
t6 = t4+t5;
t7 = Q3.*t2;
t8 = t7-Q1.*Q4.*t3;
f = [Q3;Q4;Q1.*-5.6e3-t2.*5.886e2+Q4.*t2.*t6.*6.0e1-Q4.*t3.*t8.*6.0e1+5.6e3;Q1.*t3.*5.886e2-Q3.*(t2.*t6.*6.0e1-t3.*t8.*6.0e1+Q1.*Q4.*t2.^2.*6.0e1+Q1.*Q4.*t3.^2.*6.0e1)];
