function psi_x = func_psi_x(in1)
%FUNC_PSI_X
%    PSI_X = FUNC_PSI_X(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    22-Mar-2021 15:03:26

x1 = in1(1,:);
x2 = in1(2,:);
t2 = x1.^2;
t3 = x2.^2;
psi_x = [1.0;x1;t2;t2.*x1;x2;x1.*x2;t2.*x2;t3;t3.*x1;t3.*x2];
